### ISSUE TITLE
Error reading Kaifa MA304H4

### ISSUE THREAD

**Issue by larsvinc** [endrebjorsvik/kaifa-meter#1]
Hi,

Tried using this library on my Kaifa MA304H4, using a Rapsberry PI and this USB dongle:
https://www.aliexpress.com/item/Freeshipping-USB-to-MBUS-slave-module-discrete-component-non-TSS721-circuit-M-BUS-bus-data-monitor/32814808312.html?spm=a2g0s.9042311.0.0.3da24c4dlS35K7

This is the error message I get.
Python 3.6.5 (default, Jan 10 2019, 05:08:53) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaifa_meter.reader
>>> kaifa_meter.reader.read_serial('/dev/ttyUSB0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/kaifa_meter-0.1.0-py3.6.egg/kaifa_meter/reader.py", line 56, in read_serial
AttributeError: 'int' object has no attribute 'val'

It works fine with the C-library from Per Erik Norbø. I was hoping to use your python library to pipe the data to MQTT. I would be happy to be a tester for this meter/dongle combo for your library, just instruct me on what to do.

**Comment by larsvinc** [comment]
Some more debug here (running with debug enabled)
>>> kaifa_meter.reader.read_serial('/dev/ttyUSB0')
DEBUG:Found candidate for frame start: [b'~', b'\xa0']
DEBUG:Found start of frame: [b'~', b'\xa0']
DEBUG:Frame length: 120
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/kaifa_meter-0.1.0-py3.6.egg/kaifa_meter/reader.py", line 56, in read_serial
AttributeError: 'int' object has no attribute 'val'

>>> kaifa_meter.reader.read_serial('/dev/ttyUSB0')
DEBUG:Found candidate for frame start: [b'~', b'\xa0']
DEBUG:Found start of frame: [b'~', b'\xa0']
DEBUG:Frame length: 39
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/kaifa_meter-0.1.0-py3.6.egg/kaifa_meter/reader.py", line 56, in read_serial
AttributeError: 'int' object has no attribute 'val'

**Comment by endrebjorsvik** [comment]
Thanks for pointing out that bug! And erroneous access to `val` remained after a big refactoring/cleanup. I've fixed the bug in 17b609639c0d73f61a1d0e86e2ef080795c7d411
